### ISSUE TITLE
Do not perform a CRUD read (find) when editing disabled filters

### ISSUE THREAD

**Issue by gabipetrovay** [jxmono/bind-filter#29]
The 2nd [`false`](https://github.com/jillix/bind-filter/blob/master/ui.js#L46) value is the [`dontFetchData `](https://github.com/jillix/bind-filter/blob/master/filter.js#L128). Pass `true` if the edited filter is disabled.

Please solve this direct in `master` branch without a pull request. Just move the `dev` tag around.

**Comment by silviubogan** [comment]
I made the change in the commit 6d40c0f.
